# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: V831Message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11V831Message.proto\x12\x1b\x63om.orange.navigation.proto\"\xf0\x02\n\x0bV831Message\x12H\n\nheart_beat\x18\x01 \x01(\x0b\x32\x32.com.orange.navigation.proto.V831Message.HeartBeatH\x00\x12\x44\n\x08\x64\x61ta_set\x18\x02 \x01(\x0b\x32\x30.com.orange.navigation.proto.V831Message.DataSetH\x00\x1a\x0b\n\tHeartBeat\x1a\xb8\x01\n\x07\x44\x61taSet\x12\x46\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x36.com.orange.navigation.proto.V831Message.DataSet.Event\x12\x10\n\x08periodic\x18\x02 \x01(\x08\x12\x16\n\x0erepeated_times\x18\x03 \x01(\x05\x1a;\n\x05\x45vent\x12\x10\n\x08motor_id\x18\x01 \x01(\x05\x12\x0e\n\x06period\x18\x02 \x01(\x02\x12\x10\n\x08interval\x18\x03 \x01(\x02\x42\t\n\x07\x63ontentb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'V831Message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _V831MESSAGE._serialized_start=51
  _V831MESSAGE._serialized_end=419
  _V831MESSAGE_HEARTBEAT._serialized_start=210
  _V831MESSAGE_HEARTBEAT._serialized_end=221
  _V831MESSAGE_DATASET._serialized_start=224
  _V831MESSAGE_DATASET._serialized_end=408
  _V831MESSAGE_DATASET_EVENT._serialized_start=349
  _V831MESSAGE_DATASET_EVENT._serialized_end=408
# @@protoc_insertion_point(module_scope)
